### ISSUE TITLE
hid.device.open_path TypeError: expected bytes, NoneType found

### ISSUE THREAD

**Issue by ztnewman** [keepkey/python-keepkey#100]
I have a new KeepKey that has the latest firware and was initialized via https://beta.shapeshift.com/. When I run the hello_world test script I get the following error:

```
(env) ztnewman@ztnewman:~/github/python-keepkey$ python tests/unit/*.py
.
----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
(env) znewman@znewman-l01:~/github/python-keepkey$ python helloworld.py 
Traceback (most recent call last):
  File "helloworld.py", line 34, in <module>
    main()
  File "helloworld.py", line 17, in main
    transport = HidTransport(devices[0])
  File "/home/znewman/github/python-keepkey/keepkeylib/transport_hid.py", line 78, in __init__
    super(HidTransport, self).__init__(self.path, *args, **kwargs)
  File "/home/znewman/github/python-keepkey/keepkeylib/transport.py", line 14, in __init__
    self._open()
  File "/home/znewman/github/python-keepkey/keepkeylib/transport_hid.py", line 127, in _open
    self.hid.open_path(self.device)
  File "hid.pyx", line 69, in hid.device.open_path
TypeError: expected bytes, NoneType found
```

**Comment by ayerswj** [comment]
I am having the same error
```
Python/python-keepkey/keepkeylib/transport_hid.py", line 127, in _open
    self.hid.open_path(self.device)
  File "hid.pyx", line 69, in hid.device.open_path
TypeError: expected bytes, NoneType found
```

**Comment by ztnewman** [comment]
Closing since this is quite old and I should have troubleshot more first. It was more likely an issue with the keepkey not showing up as a HID device.
