### ISSUE TITLE
hidden dependency: timeout_decorator

### ISSUE THREAD

**Issue by SomberNight** [keepkey/python-keepkey#23]
The project atm depends on [timeout_decorator](https://pypi.org/project/timeout-decorator/) but this is not explicitly declared anywhere.
It was added in https://github.com/keepkey/python-keepkey/commit/1cb4617ca9cf7c2372a774db19f96c63faf37c88

Further, timeout_decorator does not seem to work on Windows. https://github.com/pnpnpn/timeout-decorator/issues/45
I am getting
```
File "...\Python36-32\lib\site-packages\timeout_decorator\timeout_decorator.py", line 78, in new_function
    old = signal.signal(signal.SIGALRM, handler)
AttributeError: module 'signal' has no attribute 'SIGALRM'
```

**Comment by keepkeyjon** [comment]
Mind trying this out? https://github.com/keepkey/python-keepkey/pull/26

**Comment by SomberNight** [comment]
```
> python3.6 .\keepkeyctl ping "asd"
Traceback (most recent call last):
  File ".\keepkeyctl", line 506, in <module>
    main()
  File ".\keepkeyctl", line 494, in main
    client = KeepKeyClient(transport)
  File "...\python-keepkey\keepkeylib\client.py", line 479, in __init__
    self.init_device()
  File "...\python-keepkey\keepkeylib\client.py", line 486, in init_device
    self.features = expect(proto.Features)(self.call)(proto.Initialize())
  File "...\python-keepkey\keepkeylib\client.py", line 137, in wrapped_f
    ret = f(*args, **kwargs)
  File "...\python-keepkey\keepkeylib\client.py", line 150, in wrapped_f
    return f(*args, **kwargs)
  File "...\python-keepkey\keepkeylib\client.py", line 186, in call
    resp = self.call_raw(msg)
  File "...\python-keepkey\keepkeylib\client.py", line 150, in wrapped_f
    return f(*args, **kwargs)
  File "...\python-keepkey\keepkeylib\client.py", line 182, in call_raw
    return self.transport.read_blocking()
  File "...\python-keepkey\keepkeylib\transport.py", line 92, in read_blocking
    data = self._read()
  File "...\python-keepkey\keepkeylib\transport_hid.py", line 176, in _read
    (msg_type, datalen) = self._read_headers(FakeRead(self._raw_read))
  File "...\Python36-32\lib\site-packages\timeout_decorator\timeout_decorator.py", line 91, in new_function
    return timeout_wrapper(*args, **kwargs)
  File "...\Python36-32\lib\site-packages\timeout_decorator\timeout_decorator.py", line 146, in __call__
    self.__process.start()
  File "...\Python36-32\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "...\Python36-32\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "...\Python36-32\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "...\Python36-32\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "...\Python36-32\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function Transport._read_headers at 0x05458C90>: it's not the same object as keepkeylib.transport.Transport._read_headers
PS ...\python-keepkey> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "...\Python36-32\lib\multiprocessing\spawn.py", line 99, in spawn_main
    new_handle = reduction.steal_handle(parent_pid, pipe_handle)
  File "...\Python36-32\lib\multiprocessing\reduction.py", line 82, in steal_handle
    _winapi.PROCESS_DUP_HANDLE, False, source_pid)
OSError: [WinError 87] The parameter is incorrect
```
