### ISSUE TITLE
LIBUSB_ERROR_ACCESS [-3] when trying to run tests

### ISSUE THREAD

**Issue by CaptJakk** [keepkey/python-keepkey#76]
I ran: `python tests/test_basic.py`

and it resulted in this:

```
Using Keepkey over webUSB
EEE
======================================================================
ERROR: test_device_id_same (__main__.TestBasic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/keagan/start9/clients/ShapeShift/python-keepkey/tests/common.py", line 37, in setUp
    debug_transport = config.DEBUG_TRANSPORT(*config.DEBUG_TRANSPORT_ARGS, **config.DEBUG_TRANSPORT_KWARGS)
  File "/Users/keagan/start9/clients/ShapeShift/python-keepkey/env/lib/python2.7/site-packages/keepkey-6.1.0-py2.7.egg/keepkeylib/transport_webusb.py", line 62, in __init__
    super(WebUsbTransport, self).__init__(device, *args, **kwargs)
  File "/Users/keagan/start9/clients/ShapeShift/python-keepkey/env/lib/python2.7/site-packages/keepkey-6.1.0-py2.7.egg/keepkeylib/transport.py", line 14, in __init__
    self._open()
  File "/Users/keagan/start9/clients/ShapeShift/python-keepkey/env/lib/python2.7/site-packages/keepkey-6.1.0-py2.7.egg/keepkeylib/transport_webusb.py", line 73, in _open
    self.handle.claimInterface(self.interface)
  File "build/bdist.macosx-10.15-x86_64/egg/usb1/__init__.py", line 1309, in claimInterface
    libusb1.libusb_claim_interface(self.__handle, interface),
  File "build/bdist.macosx-10.15-x86_64/egg/usb1/__init__.py", line 133, in mayRaiseUSBError
    __raiseUSBError(value)
  File "build/bdist.macosx-10.15-x86_64/egg/usb1/__init__.py", line 125, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
USBErrorAccess: LIBUSB_ERROR_ACCESS [-3]

======================================================================
ERROR: test_features (__main__.TestBasic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/keagan/start9/clients/ShapeShift/python-keepkey/tests/common.py", line 37, in setUp
    debug_transport = config.DEBUG_TRANSPORT(*config.DEBUG_TRANSPORT_ARGS, **config.DEBUG_TRANSPORT_KWARGS)
  File "/Users/keagan/start9/clients/ShapeShift/python-keepkey/env/lib/python2.7/site-packages/keepkey-6.1.0-py2.7.egg/keepkeylib/transport_webusb.py", line 62, in __init__
    super(WebUsbTransport, self).__init__(device, *args, **kwargs)
  File "/Users/keagan/start9/clients/ShapeShift/python-keepkey/env/lib/python2.7/site-packages/keepkey-6.1.0-py2.7.egg/keepkeylib/transport.py", line 14, in __init__
    self._open()
  File "/Users/keagan/start9/clients/ShapeShift/python-keepkey/env/lib/python2.7/site-packages/keepkey-6.1.0-py2.7.egg/keepkeylib/transport_webusb.py", line 73, in _open
    self.handle.claimInterface(self.interface)
  File "build/bdist.macosx-10.15-x86_64/egg/usb1/__init__.py", line 1309, in claimInterface
    libusb1.libusb_claim_interface(self.__handle, interface),
  File "build/bdist.macosx-10.15-x86_64/egg/usb1/__init__.py", line 133, in mayRaiseUSBError
    __raiseUSBError(value)
  File "build/bdist.macosx-10.15-x86_64/egg/usb1/__init__.py", line 125, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
USBErrorAccess: LIBUSB_ERROR_ACCESS [-3]

======================================================================
ERROR: test_ping (__main__.TestBasic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/keagan/start9/clients/ShapeShift/python-keepkey/tests/common.py", line 37, in setUp
    debug_transport = config.DEBUG_TRANSPORT(*config.DEBUG_TRANSPORT_ARGS, **config.DEBUG_TRANSPORT_KWARGS)
  File "/Users/keagan/start9/clients/ShapeShift/python-keepkey/env/lib/python2.7/site-packages/keepkey-6.1.0-py2.7.egg/keepkeylib/transport_webusb.py", line 62, in __init__
    super(WebUsbTransport, self).__init__(device, *args, **kwargs)
  File "/Users/keagan/start9/clients/ShapeShift/python-keepkey/env/lib/python2.7/site-packages/keepkey-6.1.0-py2.7.egg/keepkeylib/transport.py", line 14, in __init__
    self._open()
  File "/Users/keagan/start9/clients/ShapeShift/python-keepkey/env/lib/python2.7/site-packages/keepkey-6.1.0-py2.7.egg/keepkeylib/transport_webusb.py", line 73, in _open
    self.handle.claimInterface(self.interface)
  File "build/bdist.macosx-10.15-x86_64/egg/usb1/__init__.py", line 1309, in claimInterface
    libusb1.libusb_claim_interface(self.__handle, interface),
  File "build/bdist.macosx-10.15-x86_64/egg/usb1/__init__.py", line 133, in mayRaiseUSBError
    __raiseUSBError(value)
  File "build/bdist.macosx-10.15-x86_64/egg/usb1/__init__.py", line 125, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
USBErrorAccess: LIBUSB_ERROR_ACCESS [-3]
```

Best I can tell this is a permissions issue with respect to pulling in the library, however, it doesn't look like libusb (which I just installed) has different ownership or permissions than anything else in `/usr/local/lib`. Any ideas on why this is?

**Comment by keepkeyjon** [comment]
Is there another client open that has exclusive control over the device? (i.e. ShapeShift platform, or the KeepKey client)

**Comment by keepkeyjon** [comment]
That could also happen if you had a release build of the firmware on the device, instead of a debug build.

**Comment by CaptJakk** [comment]
I have not modified the firmware that was on the device you gave me on Monday. No other client that I know of (brave detected it, though, so who knows), is talking to it.

**Comment by keepkeyjon** [comment]
Hm. Does it have `DEBUG_LINK` in the bottom right corner when you plug it in? That would confirm  that it's got a debug build of the firmware on it. (I might have given you the wrong thing)

**Comment by CaptJakk** [comment]
it has a little unlocked lock icon in the bottom left corner (where the cable plugs in), no other icons except keepkey branding

**Comment by keepkeyjon** [comment]
It has prod firmware then. Easy enough to fix though. You can build it with `./scripts/build/docker/device/debug.sh` from the root of the project, and then upload it to the device with `keepkeyctl firmware_update -f ./bin/firmware.keepkey.bin`.

You might also like http://github.com/solipsis/go-keepkey, which has a much better command-line than keepkeyctl.

**Comment by CaptJakk** [comment]
fixed
