### ISSUE TITLE
Issue when recompile

### ISSUE THREAD

**Issue by antonio-fr** [keepkey/python-keepkey#89]
No issue when compiling keep-keyfirmware. But when a new compilation is done with simply "make", it bugs on the ETH tokens list hashing.

# make
[  1%] Built target ssp
[  2%] Built target ssp_nonshared
[  2%] Built target kktransport.pb
[  9%] Built target kktransport
[ 24%] Built target kkboard
[ 25%] Built target kkboard.keepkey
[ 26%] Built target kkfirmware.keepkey
[ 28%] Built target qrcodegenerator
Traceback (most recent call last):
  File "/root/keepkey-firmware/deps/python-keepkey/keepkeylib/eth/ethereum_tokens.py", line 102, in <module>
    main()
  File "/root/keepkey-firmware/deps/python-keepkey/keepkeylib/eth/ethereum_tokens.py", line 90, in main
    in_digest = hashlib.sha256(inf.read().encode('utf-8')).hexdigest()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 135939: ordinal not in range(128)
make[2]: *** [lib/firmware/CMakeFiles/ethereum_tokens.def.dir/build.make:58: lib/firmware/CMakeFiles/ethereum_tokens.def] Error 1
make[1]: *** [CMakeFiles/Makefile2:391: lib/firmware/CMakeFiles/ethereum_tokens.def.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by antonio-fr** [comment]
OK, seems the issue is not linked to Python version. Something generetaed "bad" data for the toekn list and it requires a manual re-generation (python-keepkey/keepkeylib/eth/ethereum_tokens.py  lib/firmware/CMakeFiles/ethereum_tokens.def) before invoking a new make.

As I wrote here : https://github.com/keepkey/python-keepkey/pull/90#issuecomment-576225884

**Comment by antonio-fr** [comment]
I can't understand this issue. It is like python2 or 3 are mixed up? Maybe some CMake/Make recipe are not fitted good enough for tokens dep file? The def file is not generated at first pass? a cache issue ?

Maybe the issue is in https://github.com/keepkey/keepkey-firmware.

Here's the issue anyway :
```

root@srv:~/keepkey-firmware# mkdir build

root@srv:~/keepkey-firmware# cd build

root@srv:~/keepkey-firmware/build# cmake -C ../cmake/caches/device.cmake ../ -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_COLOR_MAKEFILE=ON

-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
-- The ASM compiler identification is GNU
-- Found assembler: /usr/local/bin/arm-none-eabi-gcc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at CMakeLists.txt:103 (message):
  *********************************************************************

  * You are about to build a release version of KeepKey firmware.  The *

  * resulting bootloader image will memory protect the flash on your *

  * device, so please use it with extreme care.  *

  *********************************************************************

-- Looking for strlcpy
-- Looking for strlcpy - found
-- Looking for strlcat
-- Looking for strlcat - found
-- Configuring done
-- Generating done
-- Build files have been written to: /root/keepkey-firmware/build

root@srv:~/keepkey-firmware/build# make

Scanning dependencies of target ssp
[  0%] Building C object CMakeFiles/ssp.dir/ssp.c.obj
[  1%] Linking CXX static library lib/libssp.a
[  1%] Built target ssp
Scanning dependencies of target ssp_nonshared
[  1%] Building C object CMakeFiles/ssp_nonshared.dir/ssp.c.obj
[  2%] Linking CXX static library lib/libssp_nonshared.a
[  2%] Built target ssp_nonshared
Scanning dependencies of target kktransport.pb
[  2%] Generating kktransport.pb.stamp, types.pb.c, exchange.pb.c, messages-eos.pb.c, messages-nano.pb.c, messages-cosmos.pb.c, messages.pb.c, ../../include/types.pb.h, ../../include/exchange.pb.h, ../../include/messages-eos.pb.h, ../../include/messages-nano.pb.h, ../../include/messages-cosmos.pb.h, ../../include/messages.pb.h
[  2%] Built target kktransport.pb
Scanning dependencies of target kktransport
[  3%] Building C object lib/transport/CMakeFiles/kktransport.dir/pb_common.c.obj
[  3%] Building C object lib/transport/CMakeFiles/kktransport.dir/pb_encode.c.obj
[  4%] Building C object lib/transport/CMakeFiles/kktransport.dir/pb_decode.c.obj
[  4%] Building C object lib/transport/CMakeFiles/kktransport.dir/types.pb.c.obj
[  5%] Building C object lib/transport/CMakeFiles/kktransport.dir/exchange.pb.c.obj
[  5%] Building C object lib/transport/CMakeFiles/kktransport.dir/messages-eos.pb.c.obj
[  6%] Building C object lib/transport/CMakeFiles/kktransport.dir/messages-nano.pb.c.obj
[  6%] Building C object lib/transport/CMakeFiles/kktransport.dir/messages-cosmos.pb.c.obj
[  7%] Building C object lib/transport/CMakeFiles/kktransport.dir/messages.pb.c.obj
[  8%] Linking C static library ../libkktransport.a
[  9%] Built target kktransport
Scanning dependencies of target kkboard
[ 10%] Building C object lib/board/CMakeFiles/kkboard.dir/check_bootloader.c.obj
[ 10%] Building C object lib/board/CMakeFiles/kkboard.dir/common.c.obj
[ 11%] Building C object lib/board/CMakeFiles/kkboard.dir/confirm_sm.c.obj
[ 11%] Building C object lib/board/CMakeFiles/kkboard.dir/draw.c.obj
[ 12%] Building C object lib/board/CMakeFiles/kkboard.dir/font.c.obj
[ 12%] Building C object lib/board/CMakeFiles/kkboard.dir/keepkey_board.c.obj
[ 13%] Building C object lib/board/CMakeFiles/kkboard.dir/keepkey_button.c.obj
[ 14%] Building C object lib/board/CMakeFiles/kkboard.dir/keepkey_display.c.obj
[ 14%] Building C object lib/board/CMakeFiles/kkboard.dir/keepkey_flash.c.obj
[ 15%] Building C object lib/board/CMakeFiles/kkboard.dir/keepkey_leds.c.obj
[ 15%] Building C object lib/board/CMakeFiles/kkboard.dir/keepkey_usart.c.obj
[ 16%] Building C object lib/board/CMakeFiles/kkboard.dir/layout.c.obj
[ 16%] Building C object lib/board/CMakeFiles/kkboard.dir/memory.c.obj
[ 17%] Building C object lib/board/CMakeFiles/kkboard.dir/mmhusr.c.obj
[ 18%] Building C object lib/board/CMakeFiles/kkboard.dir/messages.c.obj
[ 18%] Building C object lib/board/CMakeFiles/kkboard.dir/pin.c.obj
[ 19%] Building C object lib/board/CMakeFiles/kkboard.dir/resources.c.obj
[ 19%] Building C object lib/board/CMakeFiles/kkboard.dir/signatures.c.obj
[ 20%] Building C object lib/board/CMakeFiles/kkboard.dir/supervise.c.obj
[ 20%] Building C object lib/board/CMakeFiles/kkboard.dir/timer.c.obj
[ 21%] Building C object lib/board/CMakeFiles/kkboard.dir/usb.c.obj
[ 21%] Building C object lib/board/CMakeFiles/kkboard.dir/util.c.obj
[ 22%] Building C object lib/board/CMakeFiles/kkboard.dir/variant.c.obj
[ 23%] Building C object lib/board/CMakeFiles/kkboard.dir/usb21_standard.c.obj
[ 23%] Building C object lib/board/CMakeFiles/kkboard.dir/webusb.c.obj
[ 24%] Building C object lib/board/CMakeFiles/kkboard.dir/winusb.c.obj
[ 24%] Linking C static library ../libkkboard.a
[ 24%] Built target kkboard
Scanning dependencies of target kkboard.keepkey
[ 25%] Building C object lib/board/CMakeFiles/kkboard.keepkey.dir/variant/keepkey/resources.c.obj
[ 25%] Linking C static library ../libkkboard.keepkey.a
[ 25%] Built target kkboard.keepkey
Scanning dependencies of target kkfirmware.keepkey
[ 26%] Building C object lib/firmware/CMakeFiles/kkfirmware.keepkey.dir/variant/keepkey/resources.c.obj
[ 26%] Linking C static library ../libkkfirmware.keepkey.a
[ 26%] Built target kkfirmware.keepkey
Scanning dependencies of target qrcodegenerator
[ 27%] Building C object deps/qrenc/CMakeFiles/qrcodegenerator.dir/QR-Code-generator/c/qrcodegen.c.obj
[ 28%] Linking C static library ../../lib/libqrcodegenerator.a
[ 28%] Built target qrcodegenerator
Scanning dependencies of target ethereum_tokens.def
/root/keepkey-firmware/build/include/keepkey/firmware/ethereum_tokens.def: Updating
[ 28%] Built target ethereum_tokens.def
Scanning dependencies of target trezorcrypto
[ 28%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/bip39.c.obj
[ 29%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/bip39_english.c.obj
[ 29%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/hmac.c.obj
[ 30%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/hmac_drbg.c.obj
[ 31%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/sha2.c.obj
[ 31%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/base32.c.obj
[ 32%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/hasher.c.obj
[ 32%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/rand.c.obj
[ 33%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/rc4.c.obj
[ 33%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/blake256.c.obj
[ 34%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/cash_addr.c.obj
[ 35%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/curves.c.obj
[ 35%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/rfc6979.c.obj
[ 36%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/ed25519-donna/curve25519-donna-scalarmult-base.c.obj
[ 36%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/ed25519-donna/ed25519-donna-32bit-tables.c.obj
[ 37%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/ed25519-donna/ed25519.c.obj
[ 37%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/ed25519-donna/curve25519-donna-helpers.c.obj
[ 38%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/ed25519-donna/ed25519-blake2b.c.obj
[ 39%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/ed25519-donna/ed25519-keccak.c.obj
[ 39%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/ed25519-donna/ed25519-sha3.c.obj
[ 40%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/ed25519-donna/ed25519-donna-basepoint-table.c.obj
[ 40%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/ed25519-donna/modm-donna-32bit.c.obj
[ 41%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/ed25519-donna/curve25519-donna-32bit.c.obj
[ 41%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/ed25519-donna/ed25519-donna-impl-base.c.obj
[ 42%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/nem.c.obj
[ 42%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/nano.c.obj
[ 43%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/secp256k1.c.obj
[ 44%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/bignum.c.obj
[ 44%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/segwit_addr.c.obj
[ 45%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/ripemd160.c.obj
[ 45%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/groestl.c.obj
[ 46%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/nist256p1.c.obj
[ 46%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/memzero.c.obj
[ 47%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/blake2b.c.obj
[ 48%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/script.c.obj
[ 48%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/bip32.c.obj
[ 49%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/address.c.obj
[ 49%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/blake2s.c.obj
[ 50%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/sha3.c.obj
[ 50%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/base58.c.obj
[ 51%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/ecdsa.c.obj
[ 52%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/pbkdf2.c.obj
[ 52%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/aes/aeskey.c.obj
[ 53%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/aes/aescrypt.c.obj
[ 53%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/aes/aes_modes.c.obj
[ 54%] Building C object deps/crypto/CMakeFiles/trezorcrypto.dir/trezor-firmware/crypto/aes/aestab.c.obj
[ 54%] Linking C static library ../../lib/libtrezorcrypto.a
[ 54%] Built target trezorcrypto
Scanning dependencies of target kkfirmware
[ 55%] Building C object lib/firmware/CMakeFiles/kkfirmware.dir/app_confirm.c.obj
[ 56%] Building C object lib/firmware/CMakeFiles/kkfirmware.dir/app_layout.c.obj
[ 56%] Building C object lib/firmware/CMakeFiles/kkfirmware.dir/coins.c.obj
[ 57%] Building C object lib/firmware/CMakeFiles/kkfirmware.dir/cosmos.c.obj
[ 57%] Building C object lib/firmware/CMakeFiles/kkfirmware.dir/crypto.c.obj
[ 58%] Building C object lib/firmware/CMakeFiles/kkfirmware.dir/eos.c.obj
[ 58%] Building C object lib/firmware/CMakeFiles/kkfirmware.dir/eos-contracts/eosio.system.c.obj
[ 59%] Building C object lib/firmware/CMakeFiles/kkfirmware.dir/eos-contracts/eosio.token.c.obj
[ 60%] Building C object lib/firmware/CMakeFiles/kkfirmware.dir/ethereum.c.obj
[ 60%] Building C object lib/firmware/CMakeFiles/kkfirmware.dir/ethereum_contracts.c.obj
[ 61%] Building C object lib/firmware/CMakeFiles/kkfirmware.dir/ethereum_contracts/makerdao.c.obj
[ 61%] Building C object lib/firmware/CMakeFiles/kkfirmware.dir/ethereum_tokens.c.obj
[ 62%] Building C object lib/firmware/CMakeFiles/kkfirmware.dir/exchange.c.obj
[ 62%] Building C object lib/firmware/CMakeFiles/kkfirmware.dir/fsm.c.obj
[ 63%] Building C object lib/firmware/CMakeFiles/kkfirmware.dir/home_sm.c.obj
[ 63%] Building C object lib/firmware/CMakeFiles/kkfirmware.dir/nano.c.obj
[ 64%] Building C object lib/firmware/CMakeFiles/kkfirmware.dir/passphrase_sm.c.obj
[ 65%] Building C object lib/firmware/CMakeFiles/kkfirmware.dir/pin_sm.c.obj
[ 65%] Building C object lib/firmware/CMakeFiles/kkfirmware.dir/policy.c.obj
[ 66%] Building C object lib/firmware/CMakeFiles/kkfirmware.dir/recovery_cipher.c.obj
[ 66%] Building C object lib/firmware/CMakeFiles/kkfirmware.dir/reset.c.obj
[ 67%] Building C object lib/firmware/CMakeFiles/kkfirmware.dir/signing.c.obj
[ 67%] Building C object lib/firmware/CMakeFiles/kkfirmware.dir/storage.c.obj
[ 68%] Building C object lib/firmware/CMakeFiles/kkfirmware.dir/transaction.c.obj
[ 69%] Building C object lib/firmware/CMakeFiles/kkfirmware.dir/u2f.c.obj
[ 69%] Linking C static library ../libkkfirmware.a
[ 69%] Built target kkfirmware
Scanning dependencies of target kkrand
[ 70%] Building C object lib/rand/CMakeFiles/kkrand.dir/rng.c.obj
[ 70%] Linking C static library ../libkkrand.a
[ 70%] Built target kkrand
Scanning dependencies of target kkvariant.poweredBy
[ 70%] Building C object lib/variant/CMakeFiles/kkvariant.poweredBy.dir/poweredBy/poweredBy.c.obj
[ 71%] Building C object lib/variant/CMakeFiles/kkvariant.poweredBy.dir/poweredBy/logo.c.obj
[ 72%] Linking C static library ../libkkvariant.poweredBy.a
[ 72%] Built target kkvariant.poweredBy
Scanning dependencies of target kkvariant.keepkey
[ 73%] Building C object lib/variant/CMakeFiles/kkvariant.keepkey.dir/keepkey/keepkey.c.obj
[ 73%] Building C object lib/variant/CMakeFiles/kkvariant.keepkey.dir/keepkey/logo.c.obj
[ 74%] Linking C static library ../libkkvariant.keepkey.a
[ 74%] Built target kkvariant.keepkey
Scanning dependencies of target kkvariant.salt
[ 74%] Building C object lib/variant/CMakeFiles/kkvariant.salt.dir/salt/salt.c.obj
[ 75%] Building C object lib/variant/CMakeFiles/kkvariant.salt.dir/salt/logo.c.obj
[ 75%] Linking C static library ../libkkvariant.salt.a
[ 75%] Built target kkvariant.salt
Scanning dependencies of target bootloader.elf
[ 75%] Building C object tools/bootloader/CMakeFiles/bootloader.elf.dir/main.c.obj
[ 76%] Building C object tools/bootloader/CMakeFiles/bootloader.elf.dir/usb_flash.c.obj
[ 77%] Building C object tools/bootloader/CMakeFiles/bootloader.elf.dir/bl_mpu.c.obj
[ 77%] Building ASM object tools/bootloader/CMakeFiles/bootloader.elf.dir/startup.s.obj
[ 78%] Building ASM object tools/bootloader/CMakeFiles/bootloader.elf.dir/isr.s.obj
[ 78%] Linking C executable ../../bin/bootloader.elf
[ 78%] Built target bootloader.elf
[ 79%] Generating payload.o
Scanning dependencies of target payload
[ 79%] Linking C static library ../../lib/libpayload.a
[ 79%] Built target payload
Scanning dependencies of target blupdater.elf
[ 79%] Building C object tools/blupdater/CMakeFiles/blupdater.elf.dir/main.c.obj
[ 80%] Building ASM object tools/blupdater/CMakeFiles/blupdater.elf.dir/startup.s.obj
[ 80%] Building C object tools/blupdater/CMakeFiles/blupdater.elf.dir/__/bootloader/bl_mpu.c.obj
[ 81%] Building ASM object tools/blupdater/CMakeFiles/blupdater.elf.dir/__/bootloader/isr.s.obj
[ 81%] Building ASM object tools/blupdater/CMakeFiles/blupdater.elf.dir/header.s.obj
[ 82%] Linking C executable ../../bin/blupdater.elf
Bootloader Hash:
(stdin)= fd630fba6ad1392dbc490e5c370dc5130761321b9d1a973665ffd906d0a4fab6
[ 82%] Built target blupdater.elf
Scanning dependencies of target bootstrap.elf
[ 83%] Building C object tools/bootstrap/CMakeFiles/bootstrap.elf.dir/main.c.obj
[ 83%] Building ASM object tools/bootstrap/CMakeFiles/bootstrap.elf.dir/startup.s.obj
[ 84%] Linking C executable ../../bin/bootstrap.elf
[ 84%] Built target bootstrap.elf
Scanning dependencies of target display_test.elf
[ 85%] Building C object tools/display_test/CMakeFiles/display_test.elf.dir/main.c.obj
[ 85%] Building ASM object tools/display_test/CMakeFiles/display_test.elf.dir/startup.s.obj
[ 86%] Linking C executable ../../bin/display_test.elf
[ 86%] Built target display_test.elf
Scanning dependencies of target firmware.keepkey.elf
[ 86%] Building C object tools/firmware/CMakeFiles/firmware.keepkey.elf.dir/keepkey_main.c.obj
[ 87%] Building ASM object tools/firmware/CMakeFiles/firmware.keepkey.elf.dir/startup.s.obj
[ 87%] Building C object tools/firmware/CMakeFiles/firmware.keepkey.elf.dir/__/bootloader/bl_mpu.c.obj
[ 88%] Building ASM object tools/firmware/CMakeFiles/firmware.keepkey.elf.dir/__/bootloader/isr.s.obj
[ 88%] Building ASM object tools/firmware/CMakeFiles/firmware.keepkey.elf.dir/header.s.obj
[ 89%] Linking C executable ../../bin/firmware.keepkey.elf
[ 89%] Built target firmware.keepkey.elf
Scanning dependencies of target variant.salt.elf
[ 89%] Building C object tools/variant/CMakeFiles/variant.salt.elf.dir/salt.c.obj
[ 90%] Building ASM object tools/variant/CMakeFiles/variant.salt.elf.dir/header.s.obj
[ 91%] Linking C executable ../../bin/variant.salt.elf
[ 91%] Built target variant.salt.elf
Scanning dependencies of target variant.keepkey.elf
[ 92%] Building C object tools/variant/CMakeFiles/variant.keepkey.elf.dir/keepkey.c.obj
[ 92%] Building ASM object tools/variant/CMakeFiles/variant.keepkey.elf.dir/header.s.obj
[ 93%] Linking C executable ../../bin/variant.keepkey.elf
[ 93%] Built target variant.keepkey.elf
Scanning dependencies of target variant.fox.elf
[ 93%] Building C object tools/variant/CMakeFiles/variant.fox.elf.dir/fox.c.obj
[ 94%] Building ASM object tools/variant/CMakeFiles/variant.fox.elf.dir/header.s.obj
[ 94%] Linking C executable ../../bin/variant.fox.elf
[ 94%] Built target variant.fox.elf
Scanning dependencies of target variant.kaspersky.elf
[ 95%] Building C object tools/variant/CMakeFiles/variant.kaspersky.elf.dir/kaspersky.c.obj
[ 96%] Building ASM object tools/variant/CMakeFiles/variant.kaspersky.elf.dir/header.s.obj
[ 96%] Linking C executable ../../bin/variant.kaspersky.elf
[ 96%] Built target variant.kaspersky.elf
Scanning dependencies of target variant.blockpit.elf
[ 97%] Building C object tools/variant/CMakeFiles/variant.blockpit.elf.dir/blockpit.c.obj
[ 97%] Building ASM object tools/variant/CMakeFiles/variant.blockpit.elf.dir/header.s.obj
[ 98%] Linking C executable ../../bin/variant.blockpit.elf
[ 98%] Built target variant.blockpit.elf
Scanning dependencies of target variant.dash.elf
[ 99%] Building C object tools/variant/CMakeFiles/variant.dash.elf.dir/dash.c.obj
[ 99%] Building ASM object tools/variant/CMakeFiles/variant.dash.elf.dir/header.s.obj
[100%] Linking C executable ../../bin/variant.dash.elf
[100%] Built target variant.dash.elf

root@srv:~/keepkey-firmware/build# make

[  1%] Built target ssp
[  2%] Built target ssp_nonshared
[  2%] Built target kktransport.pb
[  9%] Built target kktransport
[ 24%] Built target kkboard
[ 25%] Built target kkboard.keepkey
[ 26%] Built target kkfirmware.keepkey
[ 28%] Built target qrcodegenerator
Traceback (most recent call last):
  File "/root/keepkey-firmware/deps/python-keepkey/keepkeylib/eth/ethereum_tokens.py", line 102, in <module>
    main()
  File "/root/keepkey-firmware/deps/python-keepkey/keepkeylib/eth/ethereum_tokens.py", line 90, in main
    in_digest = hashlib.sha256(inf.read().encode('utf-8')).hexdigest()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 135939: ordinal not in range(128)
make[2]: *** [lib/firmware/CMakeFiles/ethereum_tokens.def.dir/build.make:58: lib/firmware/CMakeFiles/ethereum_tokens.def] Error 1
make[1]: *** [CMakeFiles/Makefile2:391: lib/firmware/CMakeFiles/ethereum_tokens.def.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

root@srv:~/keepkey-firmware/build# python3 ../deps/python-keepkey/keepkeylib/eth/ethereum_tokens.py lib/firmware/CMakeFiles/ethereum_tokens.def

lib/firmware/CMakeFiles/ethereum_tokens.def: Updating

root@srv:~/keepkey-firmware/build# make

[  1%] Built target ssp
[  2%] Built target ssp_nonshared
[  2%] Built target kktransport.pb
[  9%] Built target kktransport
[ 24%] Built target kkboard
[ 25%] Built target kkboard.keepkey
[ 26%] Built target kkfirmware.keepkey
[ 28%] Built target qrcodegenerator
[ 28%] Built target ethereum_tokens.def
[ 54%] Built target trezorcrypto
[ 69%] Built target kkfirmware
[ 70%] Built target kkrand
[ 72%] Built target kkvariant.poweredBy
[ 74%] Built target kkvariant.keepkey
[ 75%] Built target kkvariant.salt
[ 78%] Built target bootloader.elf
[ 79%] Built target payload
[ 82%] Built target blupdater.elf
[ 84%] Built target bootstrap.elf
[ 86%] Built target display_test.elf
[ 89%] Built target firmware.keepkey.elf
[ 91%] Built target variant.salt.elf
[ 93%] Built target variant.keepkey.elf
[ 94%] Built target variant.fox.elf
[ 96%] Built target variant.kaspersky.elf
[ 98%] Built target variant.blockpit.elf
[100%] Built target variant.dash.elf

```

**Comment by keepkeyjon** [comment]
I was just dealing with that end of last week. Fallout from python2 vs python3 work.

It happens because there are some ERC20's which have symbols that can't be encoded. Fixed here: https://github.com/keepkey/python-keepkey/commit/e7846abe025d172a60cd8cbeb5b4ece20b3d776d#diff-683c57b786355b06ddfbd110b2b47aaeR59, but the submodule hasn't been updated yet.

**Comment by antonio-fr** [comment]
I have already checked this, the latest commit in master of this repository is even sensitive to this the bug. (If I update it the right way)

```
# git clone https://github.com/keepkey/keepkey-firmware
# cd keepkey-firmware
# git submodule update --init --recursive
  # cd deps/python-keepkey
  # git checkout master
  # git pull
# cd ../..
# mkdir build
# cd build
# cmake -C ../cmake/caches/device.cmake ../ -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_COLOR_MAKEFILE=ON
# make
# make

Traceback (most recent call last):
  File "/root/keepkey-firmware/deps/python-keepkey/keepkeylib/eth/ethereum_tokens.py", line 102, in <module>
    main()
  File "/root/keepkey-firmware/deps/python-keepkey/keepkeylib/eth/ethereum_tokens.py", line 90, in main
    in_digest = hashlib.sha256(inf.read().encode('utf-8')).hexdigest()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 135939: ordinal not in range(128)
make[2]: *** [lib/firmware/CMakeFiles/ethereum_tokens.def.dir/build.make:58: lib/firmware/CMakeFiles/ethereum_tokens.def] Error 1
make[1]: *** [CMakeFiles/Makefile2:391: lib/firmware/CMakeFiles/ethereum_tokens.def.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

```

**Comment by keepkeyjon** [comment]
oops, didn't mean to hit "close"

**Comment by keepkeyjon** [comment]
is `python` a python2 or a python3 on your machine?

**Comment by antonio-fr** [comment]
_python_ is 2 and _python3_ is 3. I think this may be the cause of the issue. Anyway, this configuration is the case for 80% of the machines.

For now, my workaround is to call :
`python3 [or python] ../deps/python-keepkey/keepkeylib/eth/ethereum_tokens.py  lib/firmware/CMakeFiles/ethereum_tokens.def`
just after the first "make". So all following _make_ are OK.

**Comment by antonio-fr** [comment]
Sorry, but this issue is still not solved using the latest commit. I don't see why closed.

```
# git clone https://github.com/keepkey/keepkey-firmware
# cd keepkey-firmware
# git submodule update --init --recursive
  # cd deps/python-keepkey
  # git checkout master
  # git pull
  # cd ../..
# mkdir build
# cd build
# cmake -C ../cmake/caches/device.cmake ../ -DCMAKE_BUILD_TYPE=MinSizeRel -DCMAKE_COLOR_MAKEFILE=ON
# make
# make
...
Traceback (most recent call last):
  File "/root/keepkey-firmware/deps/python-keepkey/keepkeylib/eth/ethereum_tokens.py", line 102, in <module>
    main()
  File "/root/keepkey-firmware/deps/python-keepkey/keepkeylib/eth/ethereum_tokens.py", line 90, in main
    in_digest = hashlib.sha256(inf.read().encode('utf-8')).hexdigest()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 135939: ordinal not in range(128)
make[2]: *** [lib/firmware/CMakeFiles/ethereum_tokens.def.dir/build.make:58: lib/firmware/CMakeFiles/ethereum_tokens.def] Error 1
make[1]: *** [CMakeFiles/Makefile2:391: lib/firmware/CMakeFiles/ethereum_tokens.def.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

The workaround is to execute the following command after the first make :
`python3 ../deps/python-keepkey/keepkeylib/eth/ethereum_tokens.py lib/firmware/CMakeFiles/ethereum_tokens.def
`

**Comment by keepkeyjon** [comment]
It closed automatically because I committed https://github.com/keepkey/python-keepkey/pull/90

**Comment by antonio-fr** [comment]
I can confirm this issue is now fixed. 👌

**Comment by keepkeyjon** [comment]
Awesome, thanks for following up! I saw your [game](https://twitter.com/a_ferron/status/1225457902791557124?s=12) the other day... nice work!
